### ISSUE TITLE
全球服务器登不上

### ISSUE THREAD

**Issue by ljwnlq** [hui-shao/ForestHelper#2]
登陆全球服务器的时候报错
Traceback (most recent call last):
File "/forest/utils/forest.py", line 1131, in <module>
if len(F.login()) <= 0:
File "/forest/utils/forest.py", line 133, in login
id info = ison.loads(r.text)
File "/usr/local/lib/python3.11/json/ init •py", line 346, in loads
return default decoder.decode ( s)
![97D49194-EB22-44DE-A19A-873D13C488B0](https://user-images.githubusercontent.com/113757208/226088501-6a8f3af5-f548-4530-9aba-7a87722e728e.png)

File "/usr/local/lib/python3.11/json/decoder.p", line 337, in decode
obj, end = self. raw_decode (s,
idx= wIs,
0) .end ( ))
File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode raise JSONDecodeError ( "Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line l column 1 (char 0)

**Comment by ljwnlq** [comment]
Traceback (most recent call last):
  File "C:\forest\ForestHelper-master\utils\forest.py", line 1131, in <module>
    if len(F.login()) <= 0:
  File "C:\forest\ForestHelper-master\utils\forest.py", line 133, in login
    id_info = json.loads(r.text)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ljwnlq** [comment]
[!] ERROR: Traceback (most recent call last):
  File "C:\forest\ForestHelper-master\utils\forest.py", line 886, in auto_plant
    return run()
  File "C:\forest\ForestHelper-master\utils\forest.py", line 785, in run
    mode_by_time_frame()
  File "C:\forest\ForestHelper-master\utils\forest.py", line 811, in mode_by_time_frame
    if self.plant_a_tree("countdown", tree_type, plant_time, note, i, _boost_by_ad, end_time):
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ljwnlq** [comment]
已自行解决
